baseURL = "https://aokiplayer.github.io/"
languageCode = "ja-jp"
title = "Yagamo Style"
theme = "theer"
# copyright = "&copy; yagamo-style.com"
disqusShortname = "shortname"
googleAnalytics = ""
# Number of posts per page
paginate = 10
enableRobotsTXT = true
hasCJKLanguage = true
uglyURLs = false

[menu]
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-road'></i>"
    url = "/posts/"
    weight = -100

[blackfriday]
  fractions = false

[params]
  shareTo = ["Twitter", "Facebook", "Hatena"]
