# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:0.55.6
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: "Git config"
          command: |
              git config --global user.name "Hiroyuki Aoki"
              git config --global user.email "aokiplayer@icloud.com"
      - add_ssh_keys:
          fingerprints:
              - "de:0d:3f:0b:55:74:25:10:00:02:55:e0:e4:a3:8e:6f"
      - run:
          name: "Build"
          command: |
              git branch -vv
              git submodule update -i # git submodule init; git submodule update
              hugo
              echo yagamo-style.com >> public/CNAME
              git add public; git commit -m "generated pages"
              git clean -fdx
      - run:
          name: "Push"
          command: |
              git checkout master
              ls -al
              echo "==== Checkout public directory from write branch"
              rm -rf ./*
              git checkout write public
              mv -f public/* .; rm -rf public
              ls -al
              git add .
              git commit -m "[ci skip] publish"
              git remote -vv
              git push origin master

