# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.11.1
      
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - add_ssh_keys:
          fingerprints:
              - "de:0d:3f:0b:55:74:25:10:00:02:55:e0:e4:a3:8e:6f"

      - checkout

      - run:
          name: hugo install
          command: |
              mkdir $HOME/src
              cd $HOME/src
              git clone https://github.com/gohugoio/hugo.git
              cd hugo
              go install
              git config --global user.name "Hiroyuki Aoki"
              git config --global user.email "aokiplayer@icloud.com"

      - run:
          name: push to master
          command: |
              git branch -vv
              # git submodule update -i
              git submodule init
              git submodule update
              hugo
              git checkout master
              git status
              ls -al
              echo "==== Checkout public directory from write branch"
              rm -rf ./*
              git checkout write public
              mv -f public/* .
              rm -rf public
              ls -al
              git add .
              git commit -m "[ci skip] publish"
              git remote -vv
              git remote set-url origin git@github.com:aokiplayer/aokiplayer.github.io.git
              git remote -vv
#              git push origin master

